Repository ghdl/ghdl, pull requests merged in 2019-09, with the labels that each got.

#925 enhance documentation terminology: reduce name clashing for VHDL standard and collections.
  doc/ghdl.texi
  doc/references/ImplementationOfVHDL.rst
  doc/using/InvokingGHDL.rst
  doc/using/QuickStartGuide.rst
Labels: CI: ReadTheDocs, Documentation: General, Enhancement

#923 readme: add cii best practices badge/shield
  README.md
Labels: Documentation: General

#928 update testsuite
  dist/travis/test.sh
  dist/travis/travis-ci.sh
  testsuite/testsuite.sh
Labels: Enhancement
