Repository ghdl/ghdl, pull requests merged in 2020-12, with the labels that each got.

#1529 synth-oper: Support Iir_Predefined_Enum_Greater{,_Equal}
  src/synth/synth-oper.adb
  testsuite/synth/enum01/tb_test.vhdl
  testsuite/synth/enum01/test.vhdl
  testsuite/synth/enum01/test_pkg.vhdl
  testsuite/synth/enum01/testsuite.sh
Labels: Enhancement, Feature: Synthesis

#1558 Executing Python unit tests in Parallel Processes
  .github/workflows/push.yml
  testsuite/pyunit/__init__.py
  testsuite/pyunit/dom/__init__.py
  testsuite/pyunit/libghdl/__init__.py
  testsuite/pyunit/pytest.ini
  testsuite/requirements.txt
  testsuite/testsuite.sh
Labels: Interface: Python, Testsuite: python

#1566 Modifications to pyGHDL.libghdl
  pyGHDL/libghdl/__init__.py
Labels: Interface: Python

#1565 Modifications to pyGHDL.libghdl.utils
  pyGHDL/libghdl/utils/__init__.py
Labels: Interface: Python

#1559 ci/msys2: split build and test
  .github/workflows/push.yml
  dist/msys2-llvm/PKGBUILD
  dist/msys2-mcode/PKGBUILD
Labels: Arch: amd64, Arch: i386, Backend: LLVM, Backend: mcode, Build: MinGW (Makefile), CI: GitHub Actions, Interface: Python, OS: Windows (MinGW), Package: Windows - MinGW (PKGBUILD), Testsuite: gna, Testsuite: python, Testsuite: sanity, Testsuite: synth, Testsuite: vests, Testsuite: vpi
