Repository ghdl/ghdl, pull requests merged in 2020-05, with the labels that each got.

#1276 doc: add hint about passing multiple '--vpi='
  doc/using/Simulation.rst
Labels: Documentation: Restructured Text, Interface: VPI

#1297 Constants in vpi
  dist/ci-run.sh
  src/grt/grt-avhpi.adb
  src/grt/grt-vcd.adb
  src/grt/grt-vpi.adb
  src/grt/grt-vpi.ads
  testsuite/testsuite.sh
  testsuite/vpi/testsuite.sh
  testsuite/vpi/vpi001/mydesign.vhdl
  testsuite/vpi/vpi001/testsuite.sh
  testsuite/vpi/vpi001/vpi1.c
  testsuite/vpi/vpi002/mydesign.vhdl
  testsuite/vpi/vpi002/testsuite.sh
  testsuite/vpi/vpi002/vpi1.c
  testsuite/vpi/vpi003/mydesign.vhdl
  testsuite/vpi/vpi003/testsuite.sh
  testsuite/vpi/vpi003/vpi1.c
Labels: Interface: VPI

#1301 Improve formatting of testenv.sh file.
  testsuite/testenv.sh
Labels: Enhancement

#1304 Adding some comments to the RTI processing.
  src/grt/grt-rtis.ads
  src/grt/grt-rtis_addr.ads
  src/grt/grt-rtis_utils.adb
Labels: Documentation: General

#1306 WIP: Add some documentation on the RTI structures.
  doc/internals/rti.rst
Labels: Documentation: Restructured Text
