Repository ghdl/ghdl, pull requests merged in 2021-06, with the labels that each got.

#1789 Added editor configuration file.
  .editorconfig
Labels: Enhancement

#1797 Add unit tests for pyGHDL DOM
  pyGHDL/requirements.txt
  testsuite/pyunit/dom/AllSources.py
  testsuite/testsuite.sh
Labels: Interface: Python

#1801 pyGHDL: add ghdl-dom entrypoint
  pyGHDL/cli/DOM.py
  setup.py
Labels: Interface: Python

#1805 Fix more codacy issues
  pyGHDL/libghdl/std_names.py
  pyGHDL/libghdl/vhdl/nodes.py
  pyGHDL/libghdl/vhdl/tokens.py
  pyGHDL/lsp/document.py
  pyGHDL/lsp/lsp.py
  pyGHDL/lsp/lsptools.py
  pyGHDL/lsp/references.py
  pyGHDL/lsp/workspace.py
  scripts/pnodes.py
  scripts/pnodespy.py
  testsuite/gna/issue283/example.py
Labels: Interface: Python

#1806 More DOM improvements
  pyGHDL/cli/DOM.py
  pyGHDL/dom/Aggregates.py
  pyGHDL/dom/Attribute.py
  pyGHDL/dom/Common.py
  pyGHDL/dom/DesignUnit.py
  pyGHDL/dom/Expression.py
  pyGHDL/dom/InterfaceItem.py
  pyGHDL/dom/Literal.py
  pyGHDL/dom/Misc.py
  pyGHDL/dom/Names.py
  pyGHDL/dom/NonStandard.py
  pyGHDL/dom/Object.py
  pyGHDL/dom/Range.py
  pyGHDL/dom/Subprogram.py
  pyGHDL/dom/Symbol.py
  pyGHDL/dom/Type.py
  pyGHDL/dom/_Translate.py
  pyGHDL/dom/_Utils.py
  pyGHDL/dom/__init__.py
  pyGHDL/dom/formatting/prettyprint.py
  pyGHDL/libghdl/__init__.py
  pyGHDL/libghdl/_decorator.py
  pyGHDL/libghdl/files_map_editor.py
  pyGHDL/requirements.txt
  setup.py
  testsuite/pyunit/Current.vhdl
  testsuite/pyunit/dom/Expressions.py
  testsuite/pyunit/dom/Literals.py
  testsuite/pyunit/dom/Sanity.py
  testsuite/pyunit/lsp/LanguageServer.py
Labels: Interface: Python

#1811 Added DLL search path for Python ≥3.8.
  pyGHDL/libghdl/__init__.py
  testsuite/pyunit/dom/Sanity.py
Labels: Interface: Python, OS: Windows (MinGW)
