Repository ghdl/ghdl, pull requests merged in 2022-03, with the labels that each got.

#1987 Fix some docs issues introduced by #1981
  doc/about.rst
  doc/using/ImplementationOfVHDL.rst
Labels: Documentation: Restructured Text

#1990 Fix a few typos
  doc/internals/RTI.rst
  doc/internals/index.rst
  doc/using/InvokingGHDL.rst
Labels: Documentation: General

#1983 vhdl-sem_decls: allow out/inout parameters to impure function in VHDL-2019
  src/vhdl/vhdl-sem_decls.adb
Labels: FeaReq: VHDL-2019
