Repository ghdl/ghdl, pull requests merged in 2022-07, with the labels that each got.

#2108 Fix docstring and a small bug in PoSh precompile script
  scripts/vendors/compile-altera.ps1
  scripts/vendors/compile-intel.ps1
  scripts/vendors/compile-lattice.ps1
  scripts/vendors/compile-osvvm.ps1
  scripts/vendors/compile-uvvm.ps1
  scripts/vendors/compile-xilinx-ise.ps1
  scripts/vendors/compile-xilinx-vivado.ps1
  scripts/vendors/shared.psm1
Labels: Precompile Scripts

#2059 fix(testsuite): show diffs on comparison failure
  testsuite/gna/issue394/testsuite.sh
  testsuite/gna/issue450/testsuite.sh
  testsuite/gna/issue719/testsuite.sh
  testsuite/gna/issue880/testsuite.sh
  testsuite/gna/ticket24/testsuite.sh
Labels: Enhancement, CI: GitHub Actions

#2127 Fix issue #2126, add handling of to_ux01 to synthesis
  src/synth/synth-vhdl_oper.adb
  testsuite/synth/issue2126/test.vhdl
  testsuite/synth/issue2126/testsuite.sh
Labels: Enhancement, Feature: Synthesis
