Repository ghdl/ghdl, pull requests merged in 2022-05, with the labels that each got.

#2057 GCC 12 compatibility
  src/ghdldrv/ghdldrv.adb
  src/ortho/mcode/ortho_code-x86-abi.adb
  src/synth/netlists-disp_dot.ads
  src/synth/netlists-inference.ads
  src/synth/synth-vhdl_stmts.adb
  src/vhdl/translate/trans-chap2.adb
  src/vhdl/translate/trans-rtis.adb
Labels: Enhancement, Backend: GCC

#2058 fix(configure): disable -Werror by default
  .github/workflows/Test.yml
  configure
  scripts/ci-run.sh
  scripts/msys2-llvm/PKGBUILD
  scripts/msys2-mcode/PKGBUILD
Labels: Enhancement, Build: Makefile, Build: MinGW (Makefile), CI: GitHub Actions

#2061 Add the -Wall flag.
  src/options.adb
Labels: Enhancement

#2069 doc: update links to Yosys website
  README.md
  doc/using/Synthesis.rst
Labels: Enhancement, Documentation: General, Documentation: Restructured Text
