Repository ghdl/ghdl, pull requests merged in 2023-03, with the labels that each got.

#2370 doc/conf: add html_theme_options
  doc/conf.py
  doc/index.rst
  doc/requirements.txt
Labels: Enhancement, Documentation: Restructured Text

#2377 news: add headings
  NEWS.md
Labels: Enhancement, Documentation: General

#2378 doc: include NEWS.md in the index
  NEWS.md
  doc/conf.py
  doc/index.rst
  doc/requirements.txt
Labels: Enhancement, Documentation: General, Documentation: Restructured Text

#2385 NEWS: update
  NEWS.md
Labels: Enhancement, Documentation: General, Documentation: Restructured Text

#2389 Limiting versions of pyTooling to >=2.13, but <3.0.
  pyGHDL/cli/requirements.txt
  pyGHDL/libghdl/requirements.txt
  pyproject.toml
Labels: Interface: Python, Dependencies
